apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-porj
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-failed.gmail: pranjulrathour3824@gmail.com
    notifications.argoproj.io/subscribe.on-sync-succeeded.gmail: pranjulrathour3824@gmail.com
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
status: {}
