apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: my-image-updater
  namespace: argocd
spec:
  writeBackConfig:
    method: "git:secret:argocd/git-creds"
    gitConfig:
      repository: "https://github.com/pranjulrathour0916/Portfolio.git"
      branch: "dev"
  applicationRefs:
    - namePattern: "portfolio"
      images:
        - alias: "portfolio"
          imageName: "pranulrathour/portfolio"
      writeBackConfig:
        method: "git:secret:argocd/git-creds"
        gitConfig:
          branch: "dev"
          writeBackTarget: "helmvalues:k8s/portfolio/values.yaml"