apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio
  namespace: argocd 
  annotations:
    # 1. Register the image with an alias
    argocd-image-updater.argoproj.io/image-list: portfolio=pranulrathour/portfolio
    # 2. Tell the updater to use Helm to update these keys
    argocd-image-updater.argoproj.io/portfolio.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/portfolio.helm.image-tag: image.tag
    # 3. (Optional) Set the update strategy
    argocd-image-updater.argoproj.io/portfolio.update-strategy: semver
spec:
  project: my-porj 
  source:
    repoURL: https://github.com/pranjulrathour0916/Portfolio.git
    targetRevision: dev 
    path: k8s/portfolio     

    helm:
      valueFiles:
        - values.yaml
    

  destination:
    server: https://kubernetes.default.svc 
    namespace: argocd
    
 
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Auto-create the target namespace if missing