name: Deploy React App

on:
  push:
    branches: [ "main", "updating" ]

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install
      - run: npm run build

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./build
      - name: Finding path
        run: pwd
      - name: build docker images
        run: 
          docker build -t ${{ secrets.DOCKER_USERNAME }}/portfolio -f dockerfile .
          
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Push Images
      - name: Push Docker Images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/portfolio

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
      
